FROM ubuntu:24.04

ARG VERSION=1.0

WORKDIR /app

RUN apt-get update -y && apt-get upgrade -y && apt-get update -y && apt-get upgrade -y
RUN apt-get install -y ca-certificates golang netcat-openbsd

COPY backend/go.mod backend/go.sum ./

RUN go mod download

COPY backend/internal/gateway/ ./internal/gateway/ 
COPY backend/cmd/gateway ./cmd/gateway
COPY backend/pkg ./pkg

RUN go build -o ./cmd/gateway/gateway ./cmd/gateway/main.go

USER nobody

EXPOSE 8080

WORKDIR /app

ENTRYPOINT ["./cmd/gateway/gateway"]