services:
  gateway:
    env_file:
      - .env
    environment:
        - GATEWAY_SERVICE_PORT=8080
    ports:
      - "${GATEWAY_PORT}:${GATEWAY_SERVICE_PORT}"
    build:
      context: ../../../  
      dockerfile: backend/deployment/docker/Dockerfile.service
      args:
        - VERSION=1.0
        - SERVICE=gateway
        - EXPOSE_PORT=8080
    container_name: gateway
    image: gateway:1.0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost $GATEWAY_SERVICE_PORT"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - local
    restart: unless-stopped
  meeting:
    env_file:
      - .env
    build:
      context: ../../../  
      dockerfile: backend/deployment/docker/Dockerfile.service
      args:
        - VERSION=1.0
        - SERVICE=meeting
        - EXPOSE_PORT=1234
    container_name: meeting
    image: meeting:1.0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost $MEETING_SERVICE_PORT"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - local
      - meeting
    depends_on:
      gateway:
        condition: service_started
    restart: unless-stopped
  request:
    env_file:
      - .env
    build:
      context: ../../../  
      dockerfile: backend/deployment/docker/Dockerfile.service
      args:
        - VERSION=1.0
        - SERVICE=request
        - EXPOSE_PORT=1337
    container_name: request
    image: request:1.0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost $REQUEST_SERVICE_PORT"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - local
      - request
    depends_on:
      gateway:
        condition: service_started
    restart: unless-stopped
  user:
    env_file:
      - .env
    build:
      context: ../../../  
      dockerfile: backend/deployment/docker/Dockerfile.service
      args:
        - VERSION=1.0
        - SERVICE=user
        - EXPOSE_PORT=9876
    container_name: user
    image: user:1.0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost $USER_SERVICE_PORT"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - local
      - user
    depends_on:
      gateway:
        condition: service_started
    restart: unless-stopped
  chat:
    env_file:
      - .env
    build:
      context: ../../../  
      dockerfile: backend/deployment/docker/Dockerfile.service
      args:
        - VERSION=1.0
        - SERVICE=chat
        - EXPOSE_PORT=5733
    container_name: chat
    image: chat:1.0
    healthcheck:
      test: ["CMD-SHELL", "nc -z localhost $CHAT_SERVICE_PORT"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - local
      - chat
    depends_on:
      gateway:
        condition: service_started
    restart: unless-stopped




  db_meeting:
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=meeting
      - PGPORT=${DB_SERVICE_PORT}
    command: -p ${DB_SERVICE_PORT}
    container_name: db_meeting
    image: db_meeting:1.0
    build: # just for the pure port number in the docker ps -a
      context: ../../../
      dockerfile: backend/deployment/docker/Dockerfile.db
      args:
      - DB_PORT=${DB_SERVICE_PORT}
    healthcheck:
      test: ["CMD-SHELL", "psql -U ${DB_USER} -d meeting -p ${DB_SERVICE_PORT} -c 'SELECT 1 FROM meetings LIMIT 1' && psql -U ${DB_USER} -d meeting -p ${DB_SERVICE_PORT} -c 'SELECT 1 FROM meeting_participants LIMIT 1'"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata_meeting:/var/lib/postgresql
      - ../../db/init-meetings.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - meeting
    depends_on:
      meeting:
        condition: service_started
    restart: unless-stopped
  db_request:
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=request
      - PGPORT=${DB_SERVICE_PORT}
    command: -p ${DB_SERVICE_PORT}
    container_name: db_request
    image: db_request:1.0
    build: # just for the pure port number in the docker ps -a
      context: ../../../
      dockerfile: backend/deployment/docker/Dockerfile.db
      args:
      - DB_PORT=${DB_SERVICE_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "postgres", "-p", "${DB_SERVICE_PORT}"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata_request:/var/lib/postgresql
    networks:
      - request
    depends_on:
      request:
        condition: service_started
    restart: unless-stopped
  db_user:
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=user
      - PGPORT=${DB_SERVICE_PORT}
    command: -p ${DB_SERVICE_PORT}
    container_name: db_user
    image: db_user:1.0
    build: # just for the pure port number in the docker ps -a
      context: ../../../
      dockerfile: backend/deployment/docker/Dockerfile.db
      args:
      - DB_PORT=${DB_SERVICE_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "postgres", "-p", "${DB_SERVICE_PORT}"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata_user:/var/lib/postgresql
    networks:
      - user
    depends_on:
      user:
        condition: service_started
    restart: unless-stopped
  db_chat:
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=chat
      - PGPORT=${DB_SERVICE_PORT}
    command: -p ${DB_SERVICE_PORT}
    container_name: db_chat
    image: db_chat:1.0 
    build: # just for the pure port number in the docker ps -a
      context: ../../../
      dockerfile: backend/deployment/docker/Dockerfile.db
      args:
      - DB_PORT=${DB_SERVICE_PORT}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER}", "-d", "postgres", "-p", "${DB_SERVICE_PORT}"]
      interval: 3s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - pgdata_chat:/var/lib/postgresql
    networks:
      - chat
    depends_on:
      chat:
        condition: service_started
    restart: unless-stopped

networks:
  local:
    driver: bridge
  user:
    driver: bridge
  meeting:
    driver: bridge
  request:
    driver: bridge
  chat:
    driver: bridge

volumes:
  pgdata_meeting:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../db/pgdata_meeting
  pgdata_request:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../db/pgdata_request
  pgdata_user:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../db/pgdata_user
  pgdata_chat:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../../db/pgdata_chat