FROM golang:1.26.4-alpine3.23

ARG VERSION=1.0
ARG SERVICE
ARG EXPOSE_PORT

WORKDIR /backend

RUN apk add --no-cache netcat-openbsd

COPY backend/go.mod backend/go.sum ./

RUN --mount=type=cache,target=/root/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go mod download

COPY backend/internal/${SERVICE}/ ./internal/${SERVICE}/ 
COPY backend/cmd/${SERVICE} ./cmd/${SERVICE}
COPY backend/pkg ./pkg
COPY backend/proto ./proto

RUN --mount=type=cache,target=/root/go/pkg/mod \
    --mount=type=cache,target=/root/.cache/go-build \
    go build -o ./cmd/${SERVICE}/${SERVICE} ./cmd/${SERVICE}/main.go

USER nobody

EXPOSE ${EXPOSE_PORT}

ENTRYPOINT ./cmd/${SERVICE}/${SERVICE}