stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

# Reusable Docker-in-Docker setup
.docker_setup: &docker_setup
  image: docker:27
  services:
    - docker:27-dind

build_backend:
  <<: *docker_setup
  stage: build
  script:
    - ls
    - cd innoconnect
    - cp .env.example .env
    - cp frontend/.env.example frontend/.env
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml build
  # optional: catch build failures early without pushing anywhere
build_frontend:
  <<: *docker_setup
  stage: build
  script:
    - ls
    - cd frontend && npm run dev
  # optional: catch build failures early without pushing anywhere

test:
  <<: *docker_setup
  stage: test
  cache:
    key: docker-layer-cache
    paths:
      - .docker-cache/
  script:
    - ls
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml build --build-arg BUILDKIT_INLINE_CACHE=1
    - echo "Testing"
  
deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cli:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "feat/36-CI/CD"'
  before_script:
    - glab auth login --job-token $CI_JOB_TOKEN --hostname $CI_SERVER_FQDN --api-protocol $CI_SERVER_PROTOCOL
    - glab -R $CI_PROJECT_PATH securefile download $SECURE_FILE_ID --path="/cd"
    - chmod 600 /cd
    - eval $(ssh-agent -s)
    - ssh-add /cd
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "cd /innoconnect && echo ALL OK"#&& git pull && docker compose up -d --build && docker compose up -d --build"