stages:
  - build
  - test
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  COMPOSE_DOCKER_CLI_BUILD: 1
  DOCKER_BUILDKIT: 1

# Reusable Docker-in-Docker setup
.docker_setup: &docker_setup
  image: docker:27
  services:
    - docker:27-dind

build_backend:
  <<: *docker_setup
  stage: build
  script:
    - ls
    - cp .env.example .env
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml build
  # optional: catch build failures early without pushing anywhere
build_frontend:
  <<: *docker_setup
  image: node:20
  stage: build
  
  script:
    - apk add --no-cache curl jq || apt-get update && apt-get install -y curl jq
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --output frontend/.env
      "https://$CI_SERVER_FQDN/api/v4/projects/$CI_PROJECT_ID/secure_files/$CI_FILE_ID/download"
    - cd frontend
    - ls
    - npm run build
  # optional: catch build failures early without pushing anywhere

test:
  <<: *docker_setup
  stage: test
  cache:
    key: docker-layer-cache
    paths:
      - .docker-cache/
  script:
    - ls
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml build --build-arg BUILDKIT_INLINE_CACHE=1
    - echo "Testing"
  
deploy:
  stage: deploy
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "feat/36-CI/CD"'
  before_script:
    - apk add --no-cache curl openssh-client
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN"
      --output deploy_key
      "https://$CI_SERVER_FQDN/api/v4/projects/$CI_PROJECT_ID/secure_files/$SSH_KEY_FILE_ID/download"
    - chmod 600 deploy_key
    - eval $(ssh-agent -s)
    - ssh-add deploy_key
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "cd /innoconnect && echo ALL OK"#&& git pull && docker compose up -d --build && docker compose up -d --build"