stages:
  - build
  - test
  - deploy

variables:
  DOCKER_BUILDKIT: 1
  COMPOSE_DOCKER_CLI_BUILD: 1

build_backend:
  stage: build
  image: docker:27
  before_script:
    - cp .env.example .env
  script:
    - ls
    - ls backend/db
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml down -v --remove-orphans || true
    - docker ps -q --filter "publish=8080" | xargs -r docker rm -f || true
    - docker rm -f gateway meeting user request chat db_meeting db_user db_request db_chat 2>/dev/null || true
    - docker system prune -af --volumes
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml build #up -d --build --wait -y
    # - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml logs -f db_user

build_frontend:
  stage: build
  image: node:20
  script:
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --output frontend/.env
      "https://$CI_SERVER_FQDN/api/v4/projects/$CI_PROJECT_ID/secure_files/$ENV_FILE_ID/download"
    - cd frontend
    - ls
    - npm install && npm install mapbox-gl react-router-dom
    - npm run build

test:
  stage: test
  image: docker:27
  before_script:
    - cp .env.example .env
  script:
    - ls
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml build
    - echo "Testing"

test_autorization:
  stage: test
  image: docker:27
  before_script:
    - cp .env.example .env
  script:
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml down -v --remove-orphans || true
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml up -d
    - apk add --no-cache curl
    - |
      status=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/meetings)
      echo "Got status: $status"
      if [ "$status" -ne 403 ]; then
        echo "FAIL: expected 403, got $status"
        exit 1
      fi
      echo "PASS: /meetings returned 403 as expected"
  after_script:
    - docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml down -v --remove-orphans || true

deploy:
  stage: deploy
  image: alpine:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "feat/36-CI/CD"'
  before_script:
    - apk add --no-cache curl openssh-client
    - >
      curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --output deploy_key
      "https://$CI_SERVER_FQDN/api/v4/projects/$CI_PROJECT_ID/secure_files/$SSH_KEY_FILE_ID/download"
    - chmod 600 deploy_key
    - eval $(ssh-agent -s)
    - ssh-add deploy_key
    - mkdir -p ~/.ssh
    - ssh-keyscan -H "$DEPLOY_HOST" >> ~/.ssh/known_hosts
  script:
    - ssh "$DEPLOY_USER@$DEPLOY_HOST" "cd /innoconnect && git fetch origin main && git checkout main && git reset --hard origin/main && git clean -fd && sudo lsof -ti:80 | xargs -r kill -9; && cd innoconnect && cp .env.example .env && docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml down &&docker compose --env-file .env -f backend/deployment/docker/docker-compose.yml up -d --build && cd frontend && cp /.env /innoconnect/frontend/.env && (npm run dev&)"