syntax = "proto3";

package request;

option go_package = "pkg/pb/request";

service RequestService {
    rpc CreateRequest(CreateRequestRequest)
        returns (RequestFull);

    rpc GetRequests(GetRequestsRequest)
        returns (GetRequestsResponse);

    rpc GetRequest(GetRequestRequest)
        returns (RequestFull);
}

message User {
    int64 id = 1;
    string name = 2;
}

message RequestShort {
    int64 id = 1;

    int64 creator_id = 2;

    string title = 3;

    string type = 4;

    string deadline = 5;
}

message RequestFull {
    int64 id = 1;

    User creator = 2;

    string title = 3;

    string description = 4;

    string requester_address = 5;

    string type = 6;

    string deadline = 7;
}

message CreateRequestRequest {
    int64 creator_id = 1;

    string creator_name = 2;

    string title = 3;

    string description = 4;

    string requester_address = 5;

    string type = 6;

    string deadline = 7;
}

message GetRequestsRequest {}

message GetRequestsResponse {
    repeated RequestShort requests = 1;
}

message GetRequestRequest {
    int64 id = 1;
}
