// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: meeting.proto

package meeting

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplyOnMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	MeetingId     int64                  `protobuf:"varint,2,opt,name=meeting_id,json=meetingId,proto3" json:"meeting_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplyOnMeetingRequest) Reset() {
	*x = ApplyOnMeetingRequest{}
	mi := &file_meeting_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplyOnMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplyOnMeetingRequest) ProtoMessage() {}

func (x *ApplyOnMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplyOnMeetingRequest.ProtoReflect.Descriptor instead.
func (*ApplyOnMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{0}
}

func (x *ApplyOnMeetingRequest) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *ApplyOnMeetingRequest) GetMeetingId() int64 {
	if x != nil {
		return x.MeetingId
	}
	return 0
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_meeting_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type MeetingShort struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       *string                `protobuf:"bytes,2,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,4,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,5,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingShort) Reset() {
	*x = MeetingShort{}
	mi := &file_meeting_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingShort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingShort) ProtoMessage() {}

func (x *MeetingShort) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingShort.ProtoReflect.Descriptor instead.
func (*MeetingShort) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{2}
}

func (x *MeetingShort) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MeetingShort) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *MeetingShort) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MeetingShort) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *MeetingShort) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type MeetingFull struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Creator       *User                  `protobuf:"bytes,4,opt,name=creator,proto3" json:"creator,omitempty"`
	Participants  []*User                `protobuf:"bytes,5,rep,name=participants,proto3" json:"participants,omitempty"`
	Address       *string                `protobuf:"bytes,6,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,8,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,9,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	MeetingTime   string                 `protobuf:"bytes,10,opt,name=meeting_time,json=meetingTime,proto3" json:"meeting_time,omitempty"`
	CurrentPeople int32                  `protobuf:"varint,11,opt,name=current_people,json=currentPeople,proto3" json:"current_people,omitempty"`
	MaxPeople     *int32                 `protobuf:"varint,12,opt,name=max_people,json=maxPeople,proto3,oneof" json:"max_people,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MeetingFull) Reset() {
	*x = MeetingFull{}
	mi := &file_meeting_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MeetingFull) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MeetingFull) ProtoMessage() {}

func (x *MeetingFull) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MeetingFull.ProtoReflect.Descriptor instead.
func (*MeetingFull) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{3}
}

func (x *MeetingFull) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MeetingFull) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MeetingFull) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MeetingFull) GetCreator() *User {
	if x != nil {
		return x.Creator
	}
	return nil
}

func (x *MeetingFull) GetParticipants() []*User {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *MeetingFull) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *MeetingFull) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MeetingFull) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *MeetingFull) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *MeetingFull) GetMeetingTime() string {
	if x != nil {
		return x.MeetingTime
	}
	return ""
}

func (x *MeetingFull) GetCurrentPeople() int32 {
	if x != nil {
		return x.CurrentPeople
	}
	return 0
}

func (x *MeetingFull) GetMaxPeople() int32 {
	if x != nil && x.MaxPeople != nil {
		return *x.MaxPeople
	}
	return 0
}

type CreateMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatorId     int64                  `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatorName   string                 `protobuf:"bytes,2,opt,name=creator_name,json=creatorName,proto3" json:"creator_name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Address       *string                `protobuf:"bytes,5,opt,name=address,proto3,oneof" json:"address,omitempty"`
	Type          string                 `protobuf:"bytes,6,opt,name=type,proto3" json:"type,omitempty"`
	Latitude      *float64               `protobuf:"fixed64,7,opt,name=latitude,proto3,oneof" json:"latitude,omitempty"`
	Longitude     *float64               `protobuf:"fixed64,8,opt,name=longitude,proto3,oneof" json:"longitude,omitempty"`
	MeetingTime   string                 `protobuf:"bytes,9,opt,name=meeting_time,json=meetingTime,proto3" json:"meeting_time,omitempty"`
	MaxPeople     *int32                 `protobuf:"varint,10,opt,name=max_people,json=maxPeople,proto3,oneof" json:"max_people,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMeetingRequest) Reset() {
	*x = CreateMeetingRequest{}
	mi := &file_meeting_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMeetingRequest) ProtoMessage() {}

func (x *CreateMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMeetingRequest.ProtoReflect.Descriptor instead.
func (*CreateMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{4}
}

func (x *CreateMeetingRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateMeetingRequest) GetCreatorName() string {
	if x != nil {
		return x.CreatorName
	}
	return ""
}

func (x *CreateMeetingRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateMeetingRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMeetingRequest) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *CreateMeetingRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateMeetingRequest) GetLatitude() float64 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *CreateMeetingRequest) GetLongitude() float64 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *CreateMeetingRequest) GetMeetingTime() string {
	if x != nil {
		return x.MeetingTime
	}
	return ""
}

func (x *CreateMeetingRequest) GetMaxPeople() int32 {
	if x != nil && x.MaxPeople != nil {
		return *x.MaxPeople
	}
	return 0
}

type GetMeetingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingsRequest) Reset() {
	*x = GetMeetingsRequest{}
	mi := &file_meeting_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingsRequest) ProtoMessage() {}

func (x *GetMeetingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingsRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingsRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{5}
}

type GetMeetingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meetings      []*MeetingShort        `protobuf:"bytes,1,rep,name=meetings,proto3" json:"meetings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingsResponse) Reset() {
	*x = GetMeetingsResponse{}
	mi := &file_meeting_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingsResponse) ProtoMessage() {}

func (x *GetMeetingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingsResponse.ProtoReflect.Descriptor instead.
func (*GetMeetingsResponse) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{6}
}

func (x *GetMeetingsResponse) GetMeetings() []*MeetingShort {
	if x != nil {
		return x.Meetings
	}
	return nil
}

type GetMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMeetingRequest) Reset() {
	*x = GetMeetingRequest{}
	mi := &file_meeting_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMeetingRequest) ProtoMessage() {}

func (x *GetMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMeetingRequest.ProtoReflect.Descriptor instead.
func (*GetMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{7}
}

func (x *GetMeetingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteMeetingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatorId     int64                  `protobuf:"varint,2,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMeetingRequest) Reset() {
	*x = DeleteMeetingRequest{}
	mi := &file_meeting_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMeetingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMeetingRequest) ProtoMessage() {}

func (x *DeleteMeetingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_meeting_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMeetingRequest.ProtoReflect.Descriptor instead.
func (*DeleteMeetingRequest) Descriptor() ([]byte, []int) {
	return file_meeting_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMeetingRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeleteMeetingRequest) GetCreatorId() int64 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

var File_meeting_proto protoreflect.FileDescriptor

const file_meeting_proto_rawDesc = "" +
	"\n" +
	"\rmeeting.proto\x12\ameeting\x1a\x1bgoogle/protobuf/empty.proto\"Y\n" +
	"\x15ApplyOnMeetingRequest\x12!\n" +
	"\x04user\x18\x01 \x01(\v2\r.meeting.UserR\x04user\x12\x1d\n" +
	"\n" +
	"meeting_id\x18\x02 \x01(\x03R\tmeetingId\"*\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"\xbc\x01\n" +
	"\fMeetingShort\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\aaddress\x18\x02 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\x12\x1f\n" +
	"\blatitude\x18\x04 \x01(\x01H\x01R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\x05 \x01(\x01H\x02R\tlongitude\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitude\"\xcc\x03\n" +
	"\vMeetingFull\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12'\n" +
	"\acreator\x18\x04 \x01(\v2\r.meeting.UserR\acreator\x121\n" +
	"\fparticipants\x18\x05 \x03(\v2\r.meeting.UserR\fparticipants\x12\x1d\n" +
	"\aaddress\x18\x06 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1f\n" +
	"\blatitude\x18\b \x01(\x01H\x01R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\t \x01(\x01H\x02R\tlongitude\x88\x01\x01\x12!\n" +
	"\fmeeting_time\x18\n" +
	" \x01(\tR\vmeetingTime\x12%\n" +
	"\x0ecurrent_people\x18\v \x01(\x05R\rcurrentPeople\x12\"\n" +
	"\n" +
	"max_people\x18\f \x01(\x05H\x03R\tmaxPeople\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\r\n" +
	"\v_max_people\"\x84\x03\n" +
	"\x14CreateMeetingRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\x03R\tcreatorId\x12!\n" +
	"\fcreator_name\x18\x02 \x01(\tR\vcreatorName\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x1d\n" +
	"\aaddress\x18\x05 \x01(\tH\x00R\aaddress\x88\x01\x01\x12\x12\n" +
	"\x04type\x18\x06 \x01(\tR\x04type\x12\x1f\n" +
	"\blatitude\x18\a \x01(\x01H\x01R\blatitude\x88\x01\x01\x12!\n" +
	"\tlongitude\x18\b \x01(\x01H\x02R\tlongitude\x88\x01\x01\x12!\n" +
	"\fmeeting_time\x18\t \x01(\tR\vmeetingTime\x12\"\n" +
	"\n" +
	"max_people\x18\n" +
	" \x01(\x05H\x03R\tmaxPeople\x88\x01\x01B\n" +
	"\n" +
	"\b_addressB\v\n" +
	"\t_latitudeB\f\n" +
	"\n" +
	"_longitudeB\r\n" +
	"\v_max_people\"\x14\n" +
	"\x12GetMeetingsRequest\"H\n" +
	"\x13GetMeetingsResponse\x121\n" +
	"\bmeetings\x18\x01 \x03(\v2\x15.meeting.MeetingShortR\bmeetings\"#\n" +
	"\x11GetMeetingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"E\n" +
	"\x14DeleteMeetingRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x02 \x01(\x03R\tcreatorId2\xf3\x02\n" +
	"\x0eMeetingService\x12E\n" +
	"\rCreateMeeting\x12\x1d.meeting.CreateMeetingRequest\x1a\x15.meeting.MeetingShort\x12H\n" +
	"\vGetMeetings\x12\x1b.meeting.GetMeetingsRequest\x1a\x1c.meeting.GetMeetingsResponse\x12>\n" +
	"\n" +
	"GetMeeting\x12\x1a.meeting.GetMeetingRequest\x1a\x14.meeting.MeetingFull\x12F\n" +
	"\rDeleteMeeting\x12\x1d.meeting.DeleteMeetingRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\x0eApplyOnMeeting\x12\x1e.meeting.ApplyOnMeetingRequest\x1a\x16.google.protobuf.EmptyB\x10Z\x0epkg/pb/meetingb\x06proto3"

var (
	file_meeting_proto_rawDescOnce sync.Once
	file_meeting_proto_rawDescData []byte
)

func file_meeting_proto_rawDescGZIP() []byte {
	file_meeting_proto_rawDescOnce.Do(func() {
		file_meeting_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_meeting_proto_rawDesc), len(file_meeting_proto_rawDesc)))
	})
	return file_meeting_proto_rawDescData
}

var file_meeting_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_meeting_proto_goTypes = []any{
	(*ApplyOnMeetingRequest)(nil), // 0: meeting.ApplyOnMeetingRequest
	(*User)(nil),                  // 1: meeting.User
	(*MeetingShort)(nil),          // 2: meeting.MeetingShort
	(*MeetingFull)(nil),           // 3: meeting.MeetingFull
	(*CreateMeetingRequest)(nil),  // 4: meeting.CreateMeetingRequest
	(*GetMeetingsRequest)(nil),    // 5: meeting.GetMeetingsRequest
	(*GetMeetingsResponse)(nil),   // 6: meeting.GetMeetingsResponse
	(*GetMeetingRequest)(nil),     // 7: meeting.GetMeetingRequest
	(*DeleteMeetingRequest)(nil),  // 8: meeting.DeleteMeetingRequest
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_meeting_proto_depIdxs = []int32{
	1, // 0: meeting.ApplyOnMeetingRequest.user:type_name -> meeting.User
	1, // 1: meeting.MeetingFull.creator:type_name -> meeting.User
	1, // 2: meeting.MeetingFull.participants:type_name -> meeting.User
	2, // 3: meeting.GetMeetingsResponse.meetings:type_name -> meeting.MeetingShort
	4, // 4: meeting.MeetingService.CreateMeeting:input_type -> meeting.CreateMeetingRequest
	5, // 5: meeting.MeetingService.GetMeetings:input_type -> meeting.GetMeetingsRequest
	7, // 6: meeting.MeetingService.GetMeeting:input_type -> meeting.GetMeetingRequest
	8, // 7: meeting.MeetingService.DeleteMeeting:input_type -> meeting.DeleteMeetingRequest
	0, // 8: meeting.MeetingService.ApplyOnMeeting:input_type -> meeting.ApplyOnMeetingRequest
	2, // 9: meeting.MeetingService.CreateMeeting:output_type -> meeting.MeetingShort
	6, // 10: meeting.MeetingService.GetMeetings:output_type -> meeting.GetMeetingsResponse
	3, // 11: meeting.MeetingService.GetMeeting:output_type -> meeting.MeetingFull
	9, // 12: meeting.MeetingService.DeleteMeeting:output_type -> google.protobuf.Empty
	9, // 13: meeting.MeetingService.ApplyOnMeeting:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_meeting_proto_init() }
func file_meeting_proto_init() {
	if File_meeting_proto != nil {
		return
	}
	file_meeting_proto_msgTypes[2].OneofWrappers = []any{}
	file_meeting_proto_msgTypes[3].OneofWrappers = []any{}
	file_meeting_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_meeting_proto_rawDesc), len(file_meeting_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_meeting_proto_goTypes,
		DependencyIndexes: file_meeting_proto_depIdxs,
		MessageInfos:      file_meeting_proto_msgTypes,
	}.Build()
	File_meeting_proto = out.File
	file_meeting_proto_goTypes = nil
	file_meeting_proto_depIdxs = nil
}
